//
// Created by Nikita Krutoy on 09.07.2021.
//

#ifndef GAME_MAGICNUMBERS_H
#define GAME_MAGICNUMBERS_H

#define MAX_ASTEROIDS_SIZE 7 // log(pixel)

#define SPACE_LENGTH 5
#define GAMEOVER_TEXT_SIZE 48
#define TITLE_TEXT_SIZE 96
#define NORMAL_TEXT_SIZE 24

#define LIGHT_BACKGROUND_MAX_BR 0.3
#define LIGHT_BACKGROUND_MIN_BR 0.1
#define DARK_BACKGROUND_MAX_BR 0.2
#define DARK_BACKGROUND_MIN_BR 0.1


#define STARS_COUNT 15
#define PLANETS_COUNT 25

#define BACKGROUND_VELOCITY 0.05
#endif //GAME_MAGICNUMBERS_H
